databases:
  - name: paperly-db
    databaseName: paperly
    user: paperly

services:
  - type: web
    name: paperly-ai
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn paperlydjango.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: paperly-db
          property: connectionString
