databases:
  - name: paperly-db
    databaseName: paperly
    user: paperly

services:
  - type: web
    name: paperly-ai
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn paperlydjango.wsgi:application --timeout 600 --workers 2 --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: paperly-db
          property: connectionString
